BG_COLOR = 'gray12'
BG_COLOR_2 = '#1c2c5c'
FG_COLOR = 'white'
FG_COLOR_ERROR = "red"
FG_COLOR_BUY = "green"
FG_COLOR_SELL = "red"
FG_COLOR_2 = 'SteelBlue1'
FG_COLOR_3 = 'gray60'
FG_COLOR_BUTTON = 'black'
GLOBAL_FONT = ('Calibri', 11, 'normal')
BOLD_FONT = ('Calibri', 11, 'bold')
BUTTON_FONT = ('Calibri', 20, 'bold')
MSG_FONT = ('Calibri', 8, 'bold')
ORD_FONT = ('Calibri', 8, 'normal')
