from tkinter import *
BG_COLOR = '#F7F7F7'
FG_COLOR = '#2196F3'
FG_COLOR_BUTTON = "#1976D2"
FG_COLOR_ERROR = "red"
FG_COLOR_BUY = "green"
FG_COLOR_SELL = "red"
FONT = ('Roboto', 13, 'normal')
LABEL_FONT = ('Roboto', 13, 'bold')
BOLD_FONT = ('Roboto', 11, 'bold')
TITLE_FONT = ('Roboto', 20, 'bold')
BUTTON_FONT = ('Roboto', 20, 'bold')
BUTTON_HEIGHT = 1
BUTTON_STICKY = W+E
BUTTON_PADX = 40
IPADX=5
IPADY=5
PADX=5
PADY=5
STICKY = W